import React, {useEffect,useRef,useState} from 'react';
import {projects} from './artworks.js';
import {resolveFilmLink} from './films.js';
import FilmPlayer from './FilmPlayer.jsx';
import {VideoBackdrop} from './Atmosphere.jsx';
const asset=file=>'/assets/'+file;
const projectURL=(id,film=false)=>'?project='+id+(film?'&view=film':'');
const Arrow=()=> <svg viewBox="0 0 32 32" fill="none" aria-hidden="true"><path d="M6 26 26 6M6 6h20v20" stroke="currentColor" strokeWidth="1.3"/></svg>;
const Close=()=> <svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="m5 5 14 14M5 19 19 5" stroke="currentColor" strokeWidth="1.25"/></svg>;
function Cover({project}){return <img src={asset(project.cover)} alt={project.title+' · 作品图像'} decoding="async"/>;}
function FilmSlot({ project, filmRef }) {
  const url=resolveFilmLink(project.id);
  return <section id="film" ref={filmRef} className={`film-slot ${url?'film-ready':''}`} aria-labelledby="film-title"><div className="film-section-heading"><span className="en">影片 / {project.number}</span><h3 id="film-title">{url?'观看影片。':'故事，等待播放。'}</h3><p>{url?'声音、动作与时间，在这里相遇。':'影片待上传。这里将连接这件作品的完整视频。'}</p></div>{url?<FilmPlayer key={project.id} src={url} poster={asset(project.cover)} title={project.title}/>:<span className="film-status">影片链接待补充 <span aria-hidden="true">↗</span></span>}</section>;
}

export default function ProjectDialog({ project, startAtFilm, onClose, onOpen, onShare, paused=false }) {
  const ref=useRef(null),close=useRef(null),film=useRef(null);const[zoom,setZoom]=useState(null);const position=projects.findIndex(p=>p.id===project.id);const next=projects[(position+1)%projects.length];
  useEffect(()=>{const before=document.activeElement;const old=document.body.style.overflow;document.body.style.overflow='hidden';close.current?.focus({preventScroll:true});return()=>{document.body.style.overflow=old;if(before?.isConnected)before.focus({preventScroll:true});};},[]);
  useEffect(()=>{const trap=event=>{if(event.key==='Escape'){if(zoom){setZoom(null);close.current?.focus({preventScroll:true});}else onClose();}if(event.key!=='Tab')return;const targets=[...ref.current.querySelectorAll('a[href],button:not([disabled]),input,video[controls],[tabindex="0"]')].filter(el=>el.offsetParent!==null);const first=targets[0],last=targets[targets.length-1];if(event.shiftKey&&(document.activeElement===first||!ref.current.contains(document.activeElement))){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}};document.addEventListener('keydown',trap);return()=>document.removeEventListener('keydown',trap);},[onClose,zoom]);
  useEffect(()=>{setZoom(null);ref.current?.scrollTo({top:0});const frame=requestAnimationFrame(()=>{if(startAtFilm)film.current?.scrollIntoView({block:'center'});});return()=>cancelAnimationFrame(frame);},[project.id,startAtFilm]);
  const showPlate=plate=>{setZoom(plate);ref.current?.scrollTo({top:0});close.current?.focus({preventScroll:true});};
  return <div className="dialog-overlay"><VideoBackdrop scene="membranes" paused={paused}/><div ref={ref} className={`project-dialog paper-section ${zoom?'plate-mode':''}`} role="dialog" aria-modal="true" aria-labelledby="project-title"><div className="dialog-bar"><span className="en">{zoom?'作品细节':'作品档案'} / {project.number}</span><div>{!zoom&&<button onClick={onShare}>复制项目链接 ↗</button>}<button ref={close} className="dialog-close" aria-label={zoom?'返回作品档案':'关闭作品档案'} onClick={()=>zoom?setZoom(null):onClose()}><span>{zoom?'返回作品':'关闭'}</span><Close/></button></div></div>{zoom?<div className="plate-view"><h2 id="project-title">{project.title} / {zoom.caption}</h2><img src={asset(zoom.src)} alt={`${project.title}：${zoom.caption}`} /><a href={asset(zoom.src)} target="_blank" rel="noopener noreferrer" className="underlined-link">打开高清原图<Arrow/></a></div>:<div className="dialog-content"><div className="project-heading"><span className="project-medium">{project.medium} <span>/</span> {project.year}</span><h2 id="project-title">{project.title}</h2><span className="project-english">{project.english}</span><div className="project-intro"><p>{project.line}</p><p>{project.summary}</p></div></div><div className={`project-cover tone-${project.tone}`}><Cover project={project} eager/></div><div className="project-notes">{project.notes.map(([heading,text],i)=><article key={heading}><span className="en">0{i+1}</span><h3>{heading}</h3><p>{text}</p></article>)}</div><FilmSlot project={project} filmRef={film}/>{project.plates.length>0&&<div className="project-archive"><div className="archive-heading"><h3>创作留下的痕迹。</h3><span className="en">草图 / 过程 / 静帧</span></div>{project.plates.map((plate,index)=><figure key={plate.src}><button onClick={()=>showPlate(plate)} aria-label={`放大查看：${plate.caption}`}><img src={asset(plate.src)} alt={`${project.title}：${plate.caption}`} loading="lazy" decoding="async"/><span>放大查看 <Arrow/></span></button><figcaption><span className="en">图版 {String(index+1).padStart(2,'0')}</span>{plate.caption}</figcaption></figure>)}</div>}{project.plates.length===0&&!resolveFilmLink(project.id)&&<p className="text-archive-note">这里呈现项目的文字档案。影片与项目图像将陆续补充。</p>}<a className="next-project" href={projectURL(next.id)} onClick={event=>{event.preventDefault();onOpen(next);}}><span className="en">下一个作品</span><strong>{next.title}</strong><Arrow/></a></div>}</div></div>;
}
